config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'bugs/index'

  get 'bugs/create'

  get 'bugs/new'

  get 'bugs/delete'

  get 'projects/index'

  get 'projects/create'

  get 'projects/new'

  get 'projects/edit'

  get 'projects/delete'

  get 'users', to: 'users#index', as: 'users'
  get 'users/new', to: 'users#new', as: 'new_user'
  get 'users/:id', to: 'users#show', as: 'user'

  post 'users', to: 'users#create'

  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'

  patch 'users/:id', to: 'users#update'

  delete 'users/:id', to: 'users#destroy', as: 'delete_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :creator, :class_name => "User", :foreign_key => "creator_id"
  belongs_to :developer, :class_name => "User", :foreign_key => "id"
  belongs_to :project, :class_name => "Project", :foreign_key => "id"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :user_projects
  has_many :user, through: :user_projects
  has_one :manager, :class_name => "User", :foreign_key => "id"
  has_many :bugs, inverse_of: 'project'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates :name, presence:true
  # validates :password, presence:true
  # validates :usertype, presence:true
  # validates :email, presence:true 
  has_many :user_projects
  has_many :projects, through: :user_projects
  has_many :bugs, :class_name => "Bug", :foreign_key => "creator_id", inverse_of: 'creator'
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def delete
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
  end

  def new
    @user=User.new
  end
  def create
    @user=User.new(user_params)
    if @user.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user=User.find(params[:id])
    @user.destroy
    redirect_to action: :index
  end
private
 def user_params
   params.require(:user).permit(:name, :email, :password, :usertype)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/create.html.erb
<h1>Bugs#create</h1>
<p>Find me in app/views/bugs/create.html.erb</p>

app/views/bugs/delete.html.erb
<h1>Bugs#delete</h1>
<p>Find me in app/views/bugs/delete.html.erb</p>

app/views/bugs/index.html.erb
<h1>Bugs#index</h1>
<p>Find me in app/views/bugs/index.html.erb</p>

app/views/bugs/new.html.erb
<h1>Bugs#new</h1>
<p>Find me in app/views/bugs/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugsinc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/delete.html.erb
<h1>Projects#delete</h1>
<p>Find me in app/views/projects/delete.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit User Data</h1>
<%= form_for @user do |user| %>
    <% if @user.errors.any? %>
    <p>There were <%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</p>
       <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
       <% end %>
    <% end %>
	<div>
		<%= user.label :name %>
	</div>
	<br>
	<div>
		<%= user.text_field :name %>
	</div>
	<div>
		<%= user.label :email %>
	</div>
	<br>
	<div>
		<%= user.text_field :email %>
	</div>
	<div>
		<%= user.label :password %>
	</div>
	<br>
	<div>
		<%= user.text_field :password %>
	</div>
	<%= user.select(:usertype, options_for_select([["Developer", "Developer"], ["QA", "QA"], ["Manager", "Manager"]], :selected => 'Developer' ), :include_blank => false) %>
	<div>
		<%= user.submit "Update Now" %>
	</div>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
 <section style="background-color: grey; width: 500px; display: flex; flex-direction: column; justify-content: center; align-items: center; margin:10px;">
 	<h2><%= link_to user.name, user_path(user)%></h2>
 	<h3>Position: <%= user.usertype%></h3>
 	<button style="width:80px;height:40px;font-size: 20px;"><%= link_to 'Edit', edit_user_path(user) %></button>
 	<button style="width:160px;height:40px;font-size: 20px;"><%= link_to 'Delete User', delete_user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user?"} %></button>
 </section>
<% end %>

app/views/users/new.html.erb
<h1>Add New User</h1>
<%= form_for @user do |user| %>
    <% if @user.errors.any? %>
    <p>There were <%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</p>
       <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
       <% end %>
    <% end %>
	<div>
		<%= user.label :name %>
	</div>
	<br>
	<div>
		<%= user.text_field :name %>
	</div>
	<div>
		<%= user.label :email %>
	</div>
	<br>
	<div>
		<%= user.text_field :email %>
	</div>
	<div>
		<%= user.label :password %>
	</div>
	<br>
	<div>
		<%= user.text_field :password %>
	</div>
	<%= user.select(:usertype, options_for_select([["Developer", "Developer"], ["QA", "QA"], ["Manager", "Manager"]], :selected => 'Developer' ), :include_blank => false) %>
	<div>
		<%= user.submit "Create Now" %>
	</div>
<% end %>

app/views/users/show.html.erb
<h1>View User Page</h1>
 <section style="background-color: grey; width: 500px; display: flex; flex-direction: column; justify-content: center; align-items: center; margin:10px;">
 	<h2><%= @user.name%></h2>
 	<h3>Position: <%= @user.usertype%></h3>
 	<button style="width:80px;height:40px;font-size: 20px;">Edit</button>
 </section>